---

- name: Install net_snmp_extra_packages
  pkgng:
    name: "{{ net_snmp_extra_packages }}"
    state: present

- name: Install net_snmp_package
  pkgng:
    name: "{{ net_snmp_package }}"
    state: present

- name: Enable net_snmp_snmptrapd_service
  service:
    name: "{{ net_snmp_snmptrapd_service }}"
    enabled: yes
  when:
    - net_snmp_snmptrapd_service_enable

- name: Enable net_snmp_service
  service:
    name: "{{ net_snmp_service }}"
    enabled: yes

- name: "Create /etc/rc.conf.d/{{ net_snmp_service }}"
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ net_snmp_service }}"
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart net_snmp_service

- name: "Create /etc/rc.conf.d/{{ net_snmp_snmptrapd_service }}"
  template:
    src: FreeBSD.rcd.snmptrapd.j2
    dest: "/etc/rc.conf.d/{{ net_snmp_snmptrapd_service }}"
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart net_snmp_snmptrapd_service
  when:
    - net_snmp_snmptrapd_service_enable
