---

- name: Install net_snmp_extra_packages
  apt:
    name: "{{ net_snmp_extra_packages }}"
    state: present

- name: Install net_snmp_package
  apt:
    name: "{{ net_snmp_package }}"
    state: present

- name: Enable net_snmp_service
  service:
    name: "{{ net_snmp_service }}"
    enabled: yes

- name: "Create /etc/default/{{ net_snmp_service }}"
  template:
    src: Debian.default.j2
    dest: "/etc/default/{{ net_snmp_service }}"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart net_snmp_service
