---

- name: Install net_snmp_extra_packages
  apt:
    name: "{{ net_snmp_extra_packages }}"
    state: present

- name: Install net_snmp_package
  apt:
    name: "{{ net_snmp_package }}"
    state: present

- name: Enable net_snmp_snmptrapd_service
  service:
    name: "{{ net_snmp_snmptrapd_service }}"
    enabled: yes
  when:
    - net_snmp_snmptrapd_service_enable

- name: Enable net_snmp_service
  service:
    name: "{{ net_snmp_service }}"
    enabled: yes

- name: Create /etc/systemd/system/snmpd.service.d
  file:
    path: /etc/systemd/system/snmpd.service.d
    state: directory
    mode: '0755'

- name: Create /etc/systemd/system/snmpd.service.d/local.conf
  template:
    src: Debian.default.j2
    dest: "/etc/systemd/system/snmpd.service.d/local.conf"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart net_snmp_service

- name: Assert net_snmp_snmptrapd_service has zero length
  # XXX the startup script of snmptrapd on Ubuntu does not read
  # /etc/default/snmptrapd (/lib/systemd/system/snmptrapd.service).
  # snmptrapd 5.7.3+dfsg-1.8ubuntu3.3
  assert:
    that:
      - net_snmp_snmptrapd_flags | length == 0
    fail_msg: "net_snmp_snmptrapd_flags is not supported on Debian/Ubuntu"
